server:
  port: 1288
  servlet:
    context-path: /api

spring:
  application:
    name: z-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/z_picture
    username: root
    password: saber

mybatis-plus:
  configuration:
    # 自动映射为驼峰字段
    map-underscore-to-camel-case: true
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    version: V1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.minesaber.zpicturebackend.controller